name: "Changed Modules"
description: "Check which parts of HPCC-Platform have been modified"
outputs:
  workflows:
    value: ${{ !fromJSON(steps.skip_checked.outputs.paths_result).workflows.should_skip || '' }}
    description: "Github Workflows"
  platform:
    value: ${{ !fromJSON(steps.skip_checked.outputs.paths_result).platform.should_skip || '' }}
    description: "HPCC-Platform"
  dockerfiles:
    value: ${{ !fromJSON(steps.skip_checked.outputs.paths_result).dockerfiles.should_skip || '' }}
    description: "Dockerfiles"
  ecllibrary:
    value: ${{ !fromJSON(steps.skip_checked.outputs.paths_result).ecllibrary.should_skip || '' }}
    description: "ECL Library"
  eclwatch:
    value: ${{ !fromJSON(steps.skip_checked.outputs.paths_result).eclwatch.should_skip || '' }}
    description: "ECL Watch"
  docs:
    value: ${{ !fromJSON(steps.skip_checked.outputs.paths_result).docs.should_skip || '' }}
    description: "Documentation"
  testing:
    value: ${{ !fromJSON(steps.skip_checked.outputs.paths_result).testing.should_skip || '' }}
    description: "Testing"
  initfiles:
    value: ${{ !fromJSON(steps.skip_checked.outputs.paths_result).initfiles.should_skip || '' }}
    description: "Init Files"
  other:
    value: ${{ !fromJSON(steps.skip_checked.outputs.paths_result).other.should_skip || '' }}
    description: "Other"

runs:
  using: "composite"
  steps:
    - id: skip_checked
      name: Skip Duplicate Action
      uses: GordonSmith/github-actions/skip-duplicate-actions@main
      with:
        github_token: ${{ github.token }}
        cancel_others: true
        paths_filter: |
          workflows:
            paths:
              - ".github/workflows/**"
          platform:
            paths:
              - "clienttools/**"
              - "cmake_modules/**"
              - "common/**"
              - "configuration/**"
              - "dali/**"
              - "deploy/**"
              - "deployment/**"
              - "ecl/**"
              - "esp/**"
              - "fs/**"
              - "lib2/**"
              - "package/**"
              - "plugins/**"
              - "roxie/**"
              - "rtl/**"
              - "services/**"
              - "system/**"
              - "thorlcr/**"
              - "tools/**"
              - "vcpkg/**"
          dockerfiles:
            paths:
              - "dockerfiles/**"
              - "helm/**"
          ecllibrary:
            paths:
              - "ecllibrary/**"
          eclwatch:
            paths:
              - "esp/src/**"
          docs:
            paths:
              - "docs/**"
          testing:
            paths:
              - "testing/**"
          initfiles:
            paths:
              - "initfiles/**"
          other:
            paths:
              - "charm/**"
              - "devdoc/**"
              - "devel/**"
              - "githooks/**"
              - "install/**"
              - "misc/**"
    - name: Changed Summary
      shell: "bash"
      run: |
        echo "workflows:  ${{ fromJSON(steps.skip_checked.outputs.paths_result).workflows.should_skip == false }}"
        echo "platform:  ${{ fromJSON(steps.skip_checked.outputs.paths_result).platform.should_skip == false }}"
        echo "dockerfiles:  ${{ fromJSON(steps.skip_checked.outputs.paths_result).dockerfiles.should_skip == false }}"
        echo "ecllibrary:  ${{ fromJSON(steps.skip_checked.outputs.paths_result).ecllibrary.should_skip == false }}"
        echo "eclwatch:  ${{ fromJSON(steps.skip_checked.outputs.paths_result).eclwatch.should_skip == false }}"
        echo "docs:  ${{ fromJSON(steps.skip_checked.outputs.paths_result).docs.should_skip == false }}"
        echo "testing:  ${{ fromJSON(steps.skip_checked.outputs.paths_result).testing.should_skip == false }}"
        echo "initfiles:  ${{ fromJSON(steps.skip_checked.outputs.paths_result).initfiles.should_skip == false }}"
        echo "other:  ${{ fromJSON(steps.skip_checked.outputs.paths_result).other.should_skip == false }}"
